### ISSUE TITLE
Bold variant of the font seems weird/broken

### ISSUE THREAD

**Issue by simonpoole** [osmfoundation/osmf-mediawiki-skin#6] opened 2018-01-24 23:02 UTC
The bold variant of the font seems to be very "uneven" in stroke width which makes it rather unpleasant  from a visual appearance  pov. This is very visible in the "Tab" and section headings.

![grafik](https://user-images.githubusercontent.com/1011860/35361768-ea7fc4ce-0162-11e8-87ff-6e38ed8444ca.png)

**Comment by nebulon42** [comment] 2018-02-05 20:12
Yes, that looks unpleasant. Which OS do you use (looks like Windows?)? It seems as you use a rather extreme setting of subpixel rendering or hinting but I'm not sure.

This is how it looks on my screen (Ubuntu 16.04 FHD display):
![screen_osmfoundation](https://user-images.githubusercontent.com/3531092/35826502-3270cfc6-0ab9-11e8-88b5-757f428d07ac.png)

**Comment by simonpoole** [comment] 2018-02-05 20:23
W10 in this case (1600*1200). For completness sake Firefox with standard settings.

**Comment by nebulon42** [comment] 2018-03-08 19:42
There might be some font rendering settings I can tweak via CSS. I'll try that. If the problem does not go away we might have to see if we need to find a different font. That would be unfortunate as I like it. :)

**Comment by nebulon42** [comment] 2018-04-29 17:48
I have switched to a slightly bolder variant to avoid the rendering problem on Windows.

**Comment by SomeoneElseOSM** [comment] 2018-05-04 10:32
Bold looks OK, but there are still problems - look at the top of the "e" (both normal and italic):

![screens_20180503_02014](https://user-images.githubusercontent.com/5311740/39623797-53027912-4f86-11e8-87d7-170dde53953e.png)

This is Firefox and Seamonkey on Windows 7 with 125% text.

**Comment by nebulon42** [comment] 2018-05-06 19:16
I'll have to check if I can use a slightly bolder variant for the normal text to avoid the aggressive subpixel hinting on Windows.

**Comment by mmd-osm** [comment] 2022-01-10 11:20
Maybe we could also try to tweak the font-size a bit. As an example, changing the value from `1.18em` to `1.15em` looks much better here (on Win10, Chrome).

1.18em:

![image](https://user-images.githubusercontent.com/5842757/148757507-f20c1b47-bd32-4306-b2c8-3aa14bd67759.png)

1.15em:

![image](https://user-images.githubusercontent.com/5842757/148757565-64142ef7-dd0a-4a53-b238-f6f025694f6d.png)

**Comment by simonpoole** [comment] 2022-01-10 12:14
IMHO the current font is a bit of a regression compared to before the style broke and @jdlrobson thankfully fixed it. At least for me the weirdness extends to the non-bold parts too, so maybe a new issue would be appropriate (I'm not quite sure why I didn't close this one way back).

**Comment by xax** [comment] 2022-04-28 16:40
On [OSMF-Wiki](https://wiki.osmfoundation.org/wiki/Main_Page) the [`osmftext`](https://github.com/osmfoundation/osmf-mediawiki-skin/blob/5605eb98c2ba3c7826d88272b1711bd397c70552/osmfoundation.less#L4-L18) font renders awfully in Opera[^1] or Vivaldi[^2] on my Win10. There is indeed ClearType activated – but tuned such that it deemed to me all other fonts render optimally.

To be able to read the OSMF Board documents I resort to apply a UserCSS changing font as a workaround…

![image](https://user-images.githubusercontent.com/673619/165799372-89534167-2092-490c-9761-d4edc4a9f569.png)
[^1]: [Opera](https://opera.com) as of any recent version, any recent Chromium engine, lets say 98 to developer's 102
[^2]: [Vivaldi](https://vivaldi.com) e.g. version 5.3, Chromium 100

**Comment by stephankn** [comment] 2022-10-05 17:39
I was recently annoyed enough about the font rendering to do a posting on community and was made aware of this existing issue. (Win 10, 100% scaling, various browsers)

I am able to reproduce the issue with the font on the fontdrop.info website, which also identified the font as **Palanquin**.
Some font sizes show extreme bad aliasing. I used the woff variant there. I assume woff2 behaves similar.

By using a more recent of the font (a modification date three years more recent), I can no longer reproduce the issue there. Could you please update the self-hosted font to a more recent version?
You can get a version for self-hosting here: https://google-webfonts-helper.herokuapp.com/fonts/palanquin?subsets=latin

**Comment by Firefishy** [comment] 2023-08-10 23:38
Just noticed this...

Could someone please retest? I have switched the font to the latest release of Palanquin. Personally I don't like the font, but kept it for now.

**Comment by Firefishy** [comment] 2023-08-11 13:41
I have had confirmation that the font issue has now been resolved on Windows. Closing, feel free to re-open if issue is still observed.

**Closed as completed by Firefishy** 2023-08-11 13:41 UTC
Labels: bug, user config

**Comment by stephankn** [comment] 2023-08-13 05:59
My eyes thank you for making the page readable again.
I explicitly confirm here on the issue tracker that it is resolved.
